# Generated by Django 4.2.2 on 2025-03-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_to_the_video",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видео",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
